apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni-management
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: cni
      targetRevision: 1.29.1
      helm:
        releaseName: istio-cni
        valueFiles:
          - $values/clusters/management/1.29.1/cni/values.yaml
    - repoURL: https://github.com/devendradk/istio-helm-values.git
      targetRevision: main
      ref: values
