apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-management
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.29.1
      helm:
        releaseName: istio-ingressgateway
        valueFiles:
          - $values/clusters/management/1.29.1/gateway/values.yaml
    - repoURL: https://github.com/devendradk/istio-helm-values.git
      targetRevision: main
      ref: values
