# Generates Application(s) for the LFS256 example repo.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  generators:
    - list:
        elements:
          - name: cert-app
            path: cert-app
            namespace: cert-app
  template:
    metadata:
      name: "cert-app-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "40"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/devendradk/LFS256-code.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
