apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-csr-management
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager-istio-csr
      targetRevision: v0.16.0
      helm:
        releaseName: istio-csr
        valueFiles:
          - $values/clusters/management/istio-csr/values.yaml
        values: |
          app:
            tls:
              # Reduce CAS issuance frequency for POC by extending istiod cert lifetime.
              istiodCertificateDuration: 720h
              istiodCertificateRenewBefore: 168h
    - repoURL: https://github.com/devendradk/platform-helm-values.git
      targetRevision: main
      ref: values
